name: Squash Resource Pack
on: [push]
jobs:
  packsquash:
    name: Squash Resource Pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      # - name: Squash
      #   uses: ComunidadAylas/PackSquash-action@v3
      #   with:
      #     path: release
      - name: Compile and upload
        uses: actions/upload-artifact@v3
        with:
          name: "tjalp's aquarium"
          path: |
               release/assets
               release/pack.mcmeta
               release/pack.png
       # Errors if files aren't found
          if-no-files-found: error